- pubspec.yaml
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...Workiva:release_pdfjs_dart_1_10_90
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...1.10.90
> Release pdfjs_dart 1.10.90

- .gitignore
- .travis.yml
- README
- README.md
- lib/pdfjs.dart
- lib/src/document_init_parameters.dart
- lib/src/pdf_document_proxy.dart
- lib/src/pdf_page_view.dart
- lib/src/pdfjs_global.dart
- pubspec.yaml
Provide support for opening documents via `DocumentInitParameters` ([documentation](https://mozilla.github.io/pdf.js/api/draft/global.html#DocumentInitParameters)). This is provided as a strongly-typed dart object which wraps a raw JS object.
Also taking this opportunity to add a couple helpful badges to the README and try to get travis passing.
> Implement `DocumentInitParameters`

- pubspec.yaml
Pulls Included in Release:
* [Implement `DocumentInitParameters`](https://github.com/Workiva/pdfjs_dart/pull/9)
Requested by: @josephmcgovern-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...Workiva:release_pdfjs_dart_1_10_90+1
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...1.10.90+1
> Release pdfjs_dart 1.10.90+1

- .gitignore
- lib/pdfjs.dart
- lib/src/page_viewport.dart
- lib/src/pdf_data_range_transport.dart
- lib/src/pdf_document_loading_task.dart
- lib/src/pdf_document_proxy.dart
- lib/src/pdf_page_proxy.dart
- lib/src/pdf_page_view.dart
Provide the necessary types and methods to support document outline and related go-to-destination functionality.
Some cleanup and a bonus API method which didn't require any type manipulation here.
> Implement `PDFDocumentProxy.getOutline()` and supporting functionality

- pubspec.yaml
Pulls Included in Release:
* [Implement `PDFDocumentProxy.getOutline()` and supporting functionality](https://github.com/Workiva/pdfjs_dart/pull/11)
Requested by: @tomconnell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...Workiva:release_pdfjs_dart_1_10_90+2
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...1.10.90+2
> Release pdfjs_dart 1.10.90+2

- smithy.yaml
The following pull request has been created by App Frameworks to help move consumers to the latest Smithy image. This was done because of an issue with Dartium and Content-Shell that would fail your CIs. Please seethis [Wiki Question](https://wiki.atl.workiva.net/cq/viewquestion.action?id=96308901&answerId=96308907)for additional context.
The following changes have been made:
* All instances of the production Smithy image have been updated to `drydock-prod.workiva.net/workiva/smithy-runner-generator:355624`.
If you have any questions, please reach out to us in the Support:H5 / Dart Hipchat room
> af_new_drydock_image

- pubspec.yaml
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/pdfjs_dart/pull/15)
* [af_new_drydock_image](https://github.com/Workiva/pdfjs_dart/pull/19)
* [HY-5956 fixes for dart 2](https://github.com/Workiva/pdfjs_dart/pull/20)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...Workiva:release_pdfjs_dart_1.10.90+4
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/1.10.90...1.10.90+4
> Release pdfjs_dart 1.10.90+4

- pubspec.yaml
* [Upgrade PDF.js to 2.1.266](https://github.com/Workiva/pdfjs_dart/pull/22)
Requested by: @theisensanders-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/1.10.90+4...Workiva:release_pdfjs_dart_2.1.266
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/1.10.90+4...2.1.266
> Release pdfjs_dart 2.1.266

- .gitignore
- .travis.yml
- Dockerfile
- analysis_options.yaml
- lib/src/document_init_parameters.dart
- lib/src/interfaces.dart
- lib/src/page_viewport.dart
- lib/src/pdf_data_range_transport.dart
- lib/src/pdf_document_loading_task.dart
- lib/src/pdf_document_proxy.dart
- lib/src/pdf_page_proxy.dart
- lib/src/pdf_page_view.dart
- lib/src/pdfjs_global.dart
- lib/src/private.dart
- pubspec.yaml
We can remove dart1.
- `dartfmt` fixes
- remove deprecated lints
- update `.travis.yaml`
- use base image
> CPLAT-8327: Post-Dart2 cleanup

- .dart_tool/package_config.json
- lib/pdfjs.dart
- lib/src/document_init_parameters.dart
- lib/src/interfaces.dart
- lib/src/page_viewport.dart
- lib/src/pdf_data_range_transport.dart
- lib/src/pdf_document_loading_task.dart
- lib/src/pdf_document_proxy.dart
- lib/src/pdf_page_proxy.dart
- lib/src/pdf_page_view.dart
- lib/src/pdfjs_global.dart
- lib/src/private.dart
- package.json
- pubspec.yaml
Ported over all the interop code from markup_client's version of 2.5.207.
Not porting over the static pdfjs files, as those are now published to the cdn via https://github.com/Workiva/pdfjs_cdn/. Available here: https://cdn-prod.wdesk.com/pdfjs_cdn/0.1.0/assets/v2.5.207
This interop has been smoke tested against pdfjs 1.10.90+4, 2.5.207 (through markup_client), and 2.7.570.
I think any consumers of this repo are pinned to old versions, so updating this interop shouldn't break anything: https://w-rmconsole.appspot.com/rosie/dependency_search/pdfjs/
1. Probably best done locally (or deployed with these branches linked below)
2. Pull this PR as a dependency_override into w_viewer (https://github.com/Workiva/w_viewer/pull/768)
3. Serve graph_app locally, with a dependency override for the …
> [INTRISK-28406] Upgrade Pdfjs interop to v2.5.207 from markup_client

- pubspec.yaml
* [CPLAT-8327: Post-Dart2 cleanup](https://github.com/Workiva/pdfjs_dart/pull/24)
* [upgrade node](https://github.com/Workiva/pdfjs_dart/pull/32)
* [[INTRISK-28406] Upgrade Pdfjs interop to v2.5.207 from markup_client](https://github.com/Workiva/pdfjs_dart/pull/35)
Requested by: @patkujawa-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.1.266...Workiva:release_pdfjs_dart_2.5.207
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.1.266...2.5.207
This pull request can be recreated by clicking …
> Release pdfjs_dart 2.5.207

- pubspec.yaml
* [upgrade node](https://github.com/Workiva/pdfjs_dart/pull/32)
* [Change to using dart_build_image for docker](https://github.com/Workiva/pdfjs_dart/pull/41)
Requested by: @pauldanner-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.5.207...Workiva:release_pdfjs_dart_2.5.207+1
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.5.207...2.5.207+1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?pull_number=42&repo_name=Workiva%2Fpdf …
> Release pdfjs_dart 2.5.207+1

- pubspec.yaml
* Minor changes:
* [INTRISK-29548: Add version safe lookup of pdfjsContext to work across pdf.js versions](https://github.com/Workiva/pdfjs_dart/pull/46)
Requested by: @pauldanner-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+1...Workiva:release_pdfjs_dart_2.5.207+2
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+1...2.5.207+2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?pull_number=47&repo_name=Workiva%2Fpdfjs_dart)
> Release pdfjs_dart 2.5.207+2

- pubspec.yaml
* [Remove deprecated authors field from pubspec.yaml](https://github.com/Workiva/pdfjs_dart/pull/30)
* [Raise the Dart SDK minimum to at least 2.11.0](https://github.com/Workiva/pdfjs_dart/pull/48)
* [Replace deprecated commands with new dart commands](https://github.com/Workiva/pdfjs_dart/pull/113)
* [Raise More Max Versions](https://github.com/Workiva/pdfjs_dart/pull/133)
Requested by: Repo Release Cron
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+2...Workiva:release_pdfjs_dart_2.5.207+3
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+2...2.5.207+3
The logs for the request that created this PR can be found …
> Release pdfjs_dart 2.5.207+3

- pubspec.yaml
* [INTRISK-43253: Add skynet.yaml to satisfy release automation](https://github.com/Workiva/pdfjs_dart/pull/137)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+3...Workiva:release_pdfjs_dart_2.5.207+4
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+3...2.5.207+4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?pull_number=138&repo_name=Workiva%2Fpdfjs_dart)
> Release pdfjs_dart 2.5.207+4

- pubspec.yaml
* Minor changes:
* [INTRISK-43815 - v2.11.338 interop](https://github.com/Workiva/pdfjs_dart/pull/140)
Requested by: @pauldanner-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+4...Workiva:release_pdfjs_dart_2.11.338
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.5.207+4...2.11.338
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=149)
> Release pdfjs_dart 2.11.338

- pubspec.yaml
* Minor changes:
* [FEDX-48 : Migrate to null safety](https://github.com/Workiva/pdfjs_dart/pull/151)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.11.338...Workiva:release_pdfjs_dart_2.12.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.11.338...2.12.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=155)
> Release pdfjs_dart 2.12.0

- pubspec.yaml
* [Dart 2.19](https://github.com/Workiva/pdfjs_dart/pull/159)
* [Start action conversion](https://github.com/Workiva/pdfjs_dart/pull/160)
* [Add CODEOWNERS](https://github.com/Workiva/pdfjs_dart/pull/162)
Requested by: Repo Release Cron
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.0...Workiva:release_pdfjs_dart_2.12.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.0...2.12.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/656813599437619 …
> Release pdfjs_dart 2.12.1

- pubspec.yaml
* [Include sbom](https://github.com/Workiva/pdfjs_dart/pull/168)
Requested by: Repo Release Cron
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.1...Workiva:release_pdfjs_dart_2.12.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.1...2.12.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=172)
> Release pdfjs_dart 2.12.2

- .github/workflows/ci.yaml
- pubspec.yaml
For Dart packages that have migrated to null safety (full or partial)
we can raise the minimum Dart SDK version to 2.19.0 instead of 2.12.0.
This will allow us to take advantage of new language features as soon as
files are migrated to null safety. We've shown that unmigrated consumers
do not have issues consuming packages with a higher minimum Dart SDK version.
- Raise minimum Dart SDK version to 2.19.0
[_Created by Sourcegraph batch change `Workiva/raise_min_dart_sdk_2_19`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/raise_min_dart_sdk_2_19)
> raise_min_dart_sdk_2_19

- lib/src/document_init_parameters.dart
There is a vulnerability in the version of PDFjs used by markup_client, and the graph/grc markup viewers. It has been addressed in a recent version of PDFjs but upgrading is not trivial. Fortunately there is a workaround. Disabling eval support prevents the attack vector.
See the ticket for repro details.
Here is a consumer for testing the fix: https://github.com/Workiva/markup_client/pull/4798
> [INTRISK-83943] default isEvalSupported to false

- pubspec.yaml
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/pdfjs_dart/pull/175)
* [[INTRISK-83943] default isEvalSupported to false](https://github.com/Workiva/pdfjs_dart/pull/184)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.2...Workiva:release_pdfjs_dart_2.12.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.2...2.12.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_d …
> Release pdfjs_dart 2.12.3

- pubspec.yaml
* [publish action](https://github.com/Workiva/pdfjs_dart/pull/187)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.3...Workiva:release_pdfjs_dart_2.12.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.3...2.12.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=188)
> Release pdfjs_dart 2.12.4

- .github/workflows/publish.yaml
The `dart-lang/setup-dart` publish GHA recently added a dependency on an action that is not certified by github and therefor not approved for use on Workiva repositories (`flutter-actions/setup-flutter`). Pinning the action to an older version for now and will request review of the action to be used in the future.
> pin publish action version

- pubspec.yaml
* [pin publish action version](https://github.com/Workiva/pdfjs_dart/pull/189)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.4...Workiva:release_pdfjs_dart_2.12.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.4...2.12.5
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=190)
> Release pdfjs_dart 2.12.5

- CHANGELOG.md
A CHANGELOG.md is required to publish a new version of the dart package
> add changelog md

- pubspec.yaml
* [add changelog md](https://github.com/Workiva/pdfjs_dart/pull/191)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.5...Workiva:release_pdfjs_dart_2.12.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.5...2.12.6
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=192)
> Release pdfjs_dart 2.12.6

- pubspec.yaml
* [addressing publish warnings](https://github.com/Workiva/pdfjs_dart/pull/193)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.12.6...Workiva:release_pdfjs_dart_2.12.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.12.6...2.12.7
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?repo_name=Workiva%2Fpdfjs_dart&pull_number=194)
> Release pdfjs_dart 2.12.7

- .github/workflows/publish.yaml
The unapproved dependency of the publish action has been approved (at the latest commit) by Workiva's infosec team (https://jira.atl.workiva.net/browse/RED-6967) and release management team (https://jira.atl.workiva.net/browse/RM-310423) meaning it can be unpinned.
> unpin publish action now that it has been approved by infosec
